# pyproject.toml
[tool.pytest.ini_options]
testpaths = [
    "tests/unit_sync",
    "tests/integration_sync",
]
pythonpath = ["pysui", "abstracts", "sui","sui/sui_types"]

[build-system]
requires = ["setuptools>=61.0","wheel"]
build-backend = "setuptools.build_meta"
